= Prerequisites
Sebastien Mosser <https://github.com/mosser[@mosser]>; Jean-Michel Bruel <https://github.com/jmbruel[@jmbruel]>

// Stuff for look & feel --------
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Variables ---------------------
:re2018url: http://www.re18.org/
:re2018: {re2018url}[RE'2018]
:re2018tuto: http://www.re18.org/tutorials.html#T02
:docker: https://docs.docker.com/[Docker]
:gherkin: http://cukes.info/gherkin.html[Gherkin]

== Development Language: Java

We will develop using the Java Language, using JDK 8+ features.

* https://www.java.com/en/download/help/download_options.xml

----
azrael:agile-tutorial mosser$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

azrael:agile-tutorial mosser$ javac -version
javac 1.8.0_102
----

== Build environment: Maven

We will use maven to take care of Java dependencies (e.g., tests frameworks)

* https://maven.apache.org/install.html

----
azrael:agile-tutorial mosser$ mvn -v
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
----

== Source code versioning

We will use the Git source code version control system.

* https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

----
azrael:agile-tutorial mosser$ git --version
git version 2.15.2 (Apple Git-101.1)
----

WARNING: Faire cloner avant

== Docker container engine

To avoid the installation of tons of different software stacks on your computer, we rely on the Docker engine to use a container-based deployment environment.

* https://docs.docker.com/install/

----
azrael:agile-tutorial mosser$ docker -v
Docker version 18.06.0-ce, build 0ffa825
----


WARNING: faire initialiser a l'avance en lançant le compose-up pour avoir les images en local
