= Reconciling Requirements and Continuous Integration in an Agile Context
Sebastien Mosser <https://github.com/mosser[@mosser]>; Jean-Michel Bruel <https://github.com/jmbruel[@jmbruel]>

// Stuff for look & feel --------
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Variables ---------------------
:re2018url: http://www.re18.org/
:re2018: {re2018url}[RE'2018]
:re2018tuto: http://www.re18.org/tutorials.html#T02
:docker: https://docs.docker.com/[Docker]
:gherkin: http://cukes.info/gherkin.html[Gherkin]
:maven: https://maven.apache.org/[Maven]
:java: https://java.com/en/download/[Java]

== Context

This tutorial is part of the {re2018} conference (see {re2018tuto}).
Do not hesitate to contact the authors to contribute or give feedback:
Sebastien Mosser <https://github.com/mosser[@mosser]> & Jean-Michel Bruel <https://github.com/jmbruel[@jmbruel]>.

== Content

This tutorial aims at exploring the boundaries between requirements, specifications, stories, scenarios and tests. Revisiting requirements elicitation and bridging the gap between traditional requirements engineering and modern software development (highly based on continuous integration and tests), this tutorial will demonstrate how to operationalize a fully-fledged tool chain going from user stories to automated acceptance testing using open-source tools. This is applicable to industrial practitioners as we will rely on state of the art tools, and link agile requirements to formal requirement engineering methods. We will first focus on the notion of user stories and epics to express user’s requirements, and how to evaluate such requirements based on “definition of ready” and “definition of done” acceptance criteria. We will then demonstrate how such requirements can be tracked in a project management tool, and linked to source code development. At the source code level, we will demonstrate how the stories and the associated acceptance scenarios can be modeled using the {gherkin} language, and linked to classical unit tests to automate their validation. Finally, a continuous integration environment will be deployed using Docker to link together the different tools and offer an automated pipeline for software developers, bridging the gap between requirements and code development.

== Requirements

NOTE: Participants are required to have {docker} installed, as well as {maven} (version 3+) and a {java} 8+ JDK. A virtual box image containing all the needed tools can be downloaded.

== Tutorial

=== Step #0: Setting up a java project

. Create a new directory, e.g., `agile-tutorial`
. inside this directory, create the following structure:
  * Business code: `src/main/java`, `src/main/resources`
  * Test code: `src/test/java`, `src/test/resources`
. Create a maven _Project Object Model_  in a file named `pom.xml` with the following contents
+
[source,xml]
----
include::pom-example.xml[]
----
+
. In a terminal, run the following command `mvn clean package`, which chould end witha  `BUILD SUCCESS` result.


=== Step #1: Creating the (product) backlog

You can use fancy web-based tools to support your backlog (_e.g._, see <<backlogtools,this list>>). For this tutorial, we'll use plain
old paper-based material. You can download the personas and story template (A4/Letter) and the kanban (A3/Tabloid) one here: TODO.

. Read the Kata description: https://codingdojo.org/kata/PokerHands/
. Start extracting usefull information:
+
[TIP]
====
* Identify the _personas_ associated to the kata description.
** Who is involved? What do they expect from the system?
* Identify the _epics_ associated to these personas.
** How to ensure that the epics are the right one?
* Refine your epics into user stories. Remember stories are made of (Persona, Action, Benefit) triplet + acceptance criteria. Also remember the _I_ of the _INVEST_ acronym (for _indepenendence_)
* Using Poker planning, identify the technical cost and the business value associated to your stories.
====
+
. Feedback
[TIP]
====
* What is difficult ? Easy ? 
* What are the roles of the epics ?
====

=== Step #2: Define a Sprint Backlog

TODO (not sure if it's the following or not)

=== Step #3: Starting a first Sprint

We are not going to start from scratch and we will consider that the initial sprint (often call "Sprint 0") has been done and that the basic code, the coding framework and the testing framework is in place.

. Download it TODO.
. Start developping the 1st story of your backlog
* Find a way to automatically validate the acceptance criteria
* Rince and repeat
. Feedback
* What do you think about developpement time ? 
* What is the role of automated acceptation ? 
* Over-engineering vs emerging architecture ? 
* How to validate the backlog ? 
* Limitations on the acceptance tests in Cucumber? 
* How to test UI ?

== References and links

* Kata:
** https://codingdojo.org/kata/PokerHands/

[[backlogtools]]
* Backlog tools (examples)
** https://easybacklog.com/
** https://trello.com/