= Reconciling Requirements and Continuous Integration in an Agile Context
Sebastien Mosser <https://github.com/mosser[@mosser]>; Jean-Michel Bruel <https://github.com/jmbruel[@jmbruel]>

// Stuff for look & feel --------
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:branch: master
:status:
:outfilesuffix: .adoc
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Variables ---------------------
:re2018url: http://www.re18.org/
:re2018: {re2018url}[RE'2018]
:re2018tuto: http://www.re18.org/tutorials.html#T02
:docker: https://docs.docker.com/[Docker]
:gherkin: http://cukes.info/gherkin.html[Gherkin]

== Context

This tutorial is part of the {re2018} conference (see {re2018tuto}).
Do not hesitate to contact the authors to contribute or give feedback:
Sebastien Mosser <https://github.com/mosser[@mosser]> & Jean-Michel Bruel <https://github.com/jmbruel[@jmbruel]>.

== Content

This tutorial aims at exploring the boundaries between requirements, specifications, stories, scenarios and tests. Revisiting requirements elicitation and bridging the gap between traditional requirements engineering and modern software development (highly based on continuous integration and tests), this tutorial will demonstrate how to operationalize a fully-fledged tool chain going from user stories to automated acceptance testing using open-source tools. This is applicable to industrial practitioners as we will rely on state of the art tools, and link agile requirements to formal requirement engineering methods. We will first focus on the notion of user stories and epics to express user’s requirements, and how to evaluate such requirements based on “definition of ready” and “definition of done” acceptance criteria. We will then demonstrate how such requirements can be tracked in a project management tool, and linked to source code development. At the source code level, we will demonstrate how the stories and the associated acceptance scenarios can be modeled using the {gherkin} language, and linked to classical unit tests to automate their validation. Finally, a continuous integration environment will be deployed using Docker to link together the different tools and offer an automated pipeline for software developers, bridging the gap between requirements and code development.

== Requirements

NOTE: Participants are required to have {docker} installed, as well as Maven (version 3+) and a Java 8+ JDK. A virtual box image containing all the needed tools can be downloaded.

== Tutorial

=== Step #0 (optional): Setting up a java project

We provide a minimal product for you to start with. If you want to start from scratch and do it on your own, please follow these instructions.

. Create a new directory, e.g., `agile-tutorial`
. inside this directory, create the following structure:
  * Business code: `src/main/java`, `src/main/resources`
  * Test code: `src/test/java`, `src/test/resources`
. Create a maven _Project Object Model_  in a file named `pom.xml` with the following contents

----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
			     http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>org.re.tutorials.agility</groupId>
  <artifactId>poker-game-kata</artifactId>
  <version>1.0</version>
  <packaging>jar</packaging>
  <name>RE'18 tutorial :: PokerGame Kata</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <finalName>poker-game</finalName>
    <defaultGoal>package</defaultGoal>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
----

[start=4]
. In a terminal, run the following command `mvn clean package`, which should end with a  `BUILD SUCCESS` result.


=== Step #1: Creating the backlog

You can use fancy web-based tools to support your backlog (_e.g._, TODO). For this tutorial, we'll use plain
old paper-based material. You can download the personas and story template (A4/Letter) and the kanban (A3/Tabloid) one here: TODO.

1. Read the Kata description: https://codingdojo.org/kata/PokerHands/

[TIP]
====
* Identify the _personas_ associated to the kata description.
** Who is involved? What do they expect from the system?
* Identify the _epics_ associated to these perosnas.
** How to ensure that the epics are the right one?
* Refine your epics into user stories. Remember stories are made of (Persona, Action, Benefit) triplet + acceptance criteria. Also remember the _I_ of the _INVEST_ acronym (for _indepenendence_)
* Using Poker planning (TODO cards), identify the technical cost and the business value associated to your stories.
====

== Step #2: Develop your MVP

We will develop our product in Java. Our product contains the following stories, making it minimal:

* As _Bob_ (a poker player), I want to give my hand's content to the croupier so that I can participate in the game;
* As _Alice_ (the croupier), I want to check the absence of card duplicates in an hand so that I can detect cheaters.

Retrieve the source code by cloning the repository on you computer:

----
$ git clone XXXXXX

----


[TIP]
====
* How to trace the
====


To support this

== References and links

- https://codingdojo.org/kata/PokerHands/
