version: '2'

services:

  # Version control system (lightweight)
  gitteaa:
    image: gitea/gitea:1.3.2
    container_name: gittea
    restart: always
    volumes:
      - ./gittea/:/data
    ports:
      - 3000:3000

  # Continuous integration server (lightweight)
  drone-server:
    image: drone/drone:0.8
    container_name: drone_server
    ports:
      - 8000:8000
      - 9000 #?
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost:8000
      - DRONE_SECRET=ThisSecretShouldBeGivenAtDeploymentTimeInsteadOfHere
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gittea:3000

  # Build agent associated to the CI server
  drone-agent:
    image: drone/agent:0.8
    container_name: drone_agent
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      # Necessary to support 'docker in docker'
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone_server:9000
      - DRONE_SECRET=ThisSecretShouldBeGivenAtDeploymentTimeInsteadOfHere