version: '2'

# To visualize the contents of this Compose file:
# docker run --rm -it --name dcv -v $(pwd):/input pmsipilot/docker-compose-viz render -m image docker-compose.yml

services:

  # Version control system (lightweight)
  gittea:
    image: gitea/gitea:1.3.2
    restart: always
    volumes:
      - ./gittea/:/data
    ports:
      - "3000:3000"

  # Continuous integration server (lightweight)
  drone-server:
    image: drone/drone:0.8
    depends_on:
      - gittea
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      # Drone Config
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server:8000
      - DRONE_SECRET=agile-tutorial-re18
      - DRONE_ADMIN=re18
      # Gittea config to hook the CI to the VCS
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gittea:3000


  # Build agent associated to the CI server
  drone-agent:
    image: drone/agent:0.8
    restart: always
    depends_on:
      - drone-server
    links:
      - gittea
    volumes:
      # Necessary to support 'docker in docker'
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=agile-tutorial-re18
      - DRONE_MAX_PROCS=3
